### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by aaronjimm** [AaronShenny/shopify#6]
![image](https://github.com/AaronShenny/shopify/assets/151840951/030ec223-5e32-4f62-90a2-93ed2704dc51)

**Comment by AaronShenny** [comment]
![image](https://github.com/AaronShenny/shopify/assets/103166950/9bcb1813-a029-4b42-9f4f-3d36ab40c90c)

**Comment by AaronShenny** [comment]
may be you didnt update the code
